apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: travel-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: travel-backend

        imagePullPolicy: Never

        ports:
        - containerPort: 5001

        envFrom:
        - configMapRef:
            name: backend-config

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI